### ISSUE TITLE
Checker piece not capturing normally

### ISSUE THREAD

**Issue by geosefuy** [KenOafallasDLSU/STSWENG_SoftwareProject#22]
When an unkinged checker piece attempts to capture another unkinged checker piece forward, the piece making the capture does not capture the other piece at all. If the move is attempted again, the move registers.

Bug Report: https://docs.google.com/document/d/11sd8WBqGOZekw-gWxx6HCHeP6ZamL2ZdlJCaRCtr4yI/edit

**Comment by counterPH** [comment]
Issue is resolved.
